name: CI
on:
 push:
   branches: [ master ]
 pull_request:
   branches: [ master ]

jobs:
  
              
  volume-test-job:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - uses: addnab/docker-run-action@v3
        with: 
            options: -v ${{ github.workspace }}:/work -e ABC=123
            image: ghcr.io/aad-for-linux/pam_aad:ubuntu
            run: |
              cd work
              ./bootstrap.sh
              ./configure --with-pam-dir=/lib/x86_64-linux-gnu/security/
              make
              sudo make install
              ls
